name: CD

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: ğŸ™ Generate new release
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: â¬‡ï¸ Checkout project
        uses: actions/checkout@v2

      - name: ğŸ» Build and generate new release
        uses: softprops/action-gh-release@v1
        with:
          body_path: CHANGELOG.md
          token: ${{ secrets.GITHUB_TOKEN }}

  distribute:
    name: ğŸ›©ï¸ Deliver project
    runs-on: ubuntu-latest
    needs: release

    steps:
      - name: â¬‡ï¸ Checkout project
        uses: actions/checkout@v2

      - name: ğŸ·ï¸ Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: ğŸ’½ Build OCI image
        run: make build/prod TAG=${{ steps.get_version.outputs.VERSION }}
